### ISSUE TITLE
GUI Feature

### ISSUE THREAD

**Issue by dylib** [tylwright/PyOSX-Info#2]
I have a question about your screenshot showing off PyOSX-Info:

![cap](https://cloud.githubusercontent.com/assets/17288131/13908276/a7c8bf24-eebc-11e5-9d7a-00e9bcc0241b.png)

Is this a standard Terminal.app window or is it Xterm, and what are you using to create the custom prompt (eg. `~/Desktop/PyOSX-Info | dev`)? Thanks!

**Comment by tylwright** [comment]
Hi @dylib 

I'm using iTerm instead of Terminal.  Also, I get the custom prompt by using a couple of things: ZSH instead of Bash along with a ZSH theme called "agnoster."

If you're new to ZSH, I highly recommend oh-my-zsh (https://github.com/robbyrussell/oh-my-zsh).  I believe it contains the agnoster theme by default too!
